import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import { homelink, link } from '../data/linkdata'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>TODO</h1>
      <ul>
        {homelink.map((item:link,index:number)=>(
          <li key={index}>
            <Link href={item.link} target={item.target}>
              {item.name}
            </Link>
          </li>
        ))}
      </ul>
    </>
  )
}
